name: Publish to npm

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 0.3.0)'
        required: true
        default: '0.3.0'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install dependencies
        working-directory: js-bindings
        run: bun install
      
      - name: Run tests
        working-directory: js-bindings
        run: bun run test-all-features.ts
      
      - name: Verify WASM exists
        run: |
          if [ ! -f "js-bindings/dhi.wasm" ]; then
            echo "Error: dhi.wasm not found!"
            exit 1
          fi
          echo "WASM file size: $(ls -lh js-bindings/dhi.wasm | awk '{print $5}')"
      
      - name: Update version
        if: github.event.inputs.version
        working-directory: js-bindings
        run: |
          npm version ${{ github.event.inputs.version }} --no-git-tag-version
      
      - name: Publish to npm
        working-directory: js-bindings
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## dhi v${{ github.ref_name }}
            
            **Ultra-fast validation library - 1.64x faster than Zod!**
            
            ### Performance
            - TURBO mode: 40.26M ops/sec
            - Batch API: 8.19x faster on mixed data
            - Feature-complete: 100% Zod compatible
            
            ### Installation
            ```bash
            npm install dhi@${{ github.ref_name }}
            ```
            
            ### What's New
            See CHANGELOG.md for details.
          draft: false
          prerelease: false
